name: Report Size Deltas

on:
  schedule:
    - cron: "*/5 * * * *"
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Comment size deltas reports to PRs
        uses: arduino/report-size-deltas@v1
        with:
          # The name of the workflow artifact created by the "Compile Examples" workflow
          sketches-reports-source: sketches-reports
