#ALTERNATE_CORE = attiny
#BOARD_TAG    = attiny85-8
BOARD_TAG    = uno
MONITOR_PORT = usb
ARDUINO_LIBS = 
#F_CPU = 8000000L
AVRDUDE_ARD_PROGRAMMER = dragon_hvsp

include /home/tonym/personal/electronics/arduino-1.0.5-with-attiny85/Arduino-Makefile-master/Arduino.mk

